---
title: "Day 3 — Wednesday, January 11th, 2022"
sidebar:
  style: "floating"
  search: true
  contents: auto
---

## Wednesday January 11th

  * 1:30-2:00 Lecture: R Projects
  * 2:00-2:50 Lecture: Intro to dplyr
  * 2:50-3:10 Activity: Work on dplyr learnr tutorial in groups
  * 3:10-3:15 Break
  * 3:15-3:45 Lecture: Cleaning Text Data
  * 3:45-4:10 Lecture: Writing Functions
  * 4:10-4:30 Activity: Write functions together
  * 4:30-4:45 Activity: Discussion Q&A from ggplot2 Homework
  * 4:45-4:55 Survey: Checking in on Pacing
  * 4:55-5:10 Demonstration of how to do the homework 
  * 5:10-5:30 Time to work on homework, chat with classmates, peruse recommended materials
  
### Recommended reading: 

  * On Projects: 
    - Tidyverse Blog, Project-Oriented Workflow by Jenny Bryan: <https://www.tidyverse.org/blog/2017/12/workflow-vs-script/> 
    - R for Data Science, Chapter 8: <https://r4ds.had.co.nz/workflow-projects.html>
    - Project-Oriented Workflow, Jenny Bryan <https://www.tidyverse.org/blog/2017/12/workflow-vs-script/>
  * On dplyr, cleaning text, and writing functions
    - R for Data Science, Chapter 5 Data Transformation: <https://r4ds.had.co.nz/transform.html>
    - R for Data Science, Chapter 14 Strings:  <https://r4ds.had.co.nz/strings.html>
    - R for Data Science, Chapter 19 Functions: <https://r4ds.had.co.nz/functions.html> 
    
### Homework: 

  - No homework
  
## Video Recording

<iframe width="100%" height="500" src="https://www.youtube.com/embed/g5s2jibMhAk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Resources
<a href="https://docs.google.com/document/d/1F5rgKfnvoyrj8gsbH-yP5XgTkDm2uUvJLQExhm7UlTA/edit?usp=share_link"> link to daily google doc </a>
<br>
<a href="https://drive.google.com/drive/folders/1lTmPCQhHdcXlf0CB8L6TopFvJ6x7kO4b?usp=share_link"> link to PDF slides </a>



### Lecture 1: Projects in RStudio
<iframe src="https://id529.github.io/lectures/day3/lecture1-projects-in-rstudio/r-projects.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures/day3/lecture1-projects-in-rstudio/r-projects.html" >link to view slides fullscreen</iframe>

### Lecture 2: Intro to dplyr
<iframe src="https://id529.github.io/lectures/day3/lecture2-intro-to-dplyr/intro-to-dplyr.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures/day3/lecture2-intro-to-dplyr/intro-to-dplyr.html" >link to view slides fullscreen</iframe>

### Lecture 4: Cleaning Text Data
<iframe src="https://id529.github.io/lectures/day3/lecture4-cleaning-text-data/cleaning-text-data.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures/day3/lecture4-cleaning-text-data/cleaning-text-data.html" >link to view slides fullscreen</iframe>


### Lecture 5: Functions
<iframe src="https://id529.github.io/lectures/day3/lecture5-functions/functions.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures/day3/lecture5-functions/functions.html" >link to view slides fullscreen</iframe>
