---
title: "Day 5 — Friday, January 13th, 2022"
sidebar:
  style: "floating"
  search: true
  contents: auto
---

## Friday January 13th

  * 1:30-2:00 Lecture: Why reproducibility and robustness are important
  principles in science and data analysis and acknowledging the pressures in
  academia that push people away from reproducible science
  * 2:00-2:15 Discussion
  * 2:15-2:45 Lecture: Visualizing and Reporting on Regression Models
  * 2:45-3:05 Lecture: Data Linkage Methods
  * 3:05-3:25 Activity: Working with Joins 
  * 3:25-3:35 Break
  * 3:35-4:00 Activity: Hallway QR Code Challenges
  * 4:00-4:15 Lecture: Introduction of the Brown et al (partial) reproduction of Onikye et al's results
  * 4:15-4:30 Homework demonstration
  * 4:30-5:25 Time to work on homework + chat together + work on final projects 
  * 5:25-5:30 Giveaway for a Copy of R for Data Science
  * 5:30 Meet Hodu!
  
### Homework 4

  * Read the Brown et al reproduction of Onikye et al, run their code, and fill out the worksheet
    * https://open.lnu.se/index.php/metapsychology/article/view/2071
    * https://osf.io/j32yw/ 
  * Peer review for homework 3
  
### Available/Recommended Materials:

  * Reproducibility:
    * *Draw Me A Project* <https://masalmon.eu/2021/06/30/r-projects/>
    * *Reproducibility of Scientific Results* <https://plato.stanford.edu/entries/scientific-reproducibility/>
    * *Best Practices for Scientific Computing* <https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745>
    * *Good Enough Practices for Scientific Computing* <https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510>
    * *Replicability, Robustness, and Reproducibility in Psychological Science* <https://pure.uvt.nl/ws/portalfiles/portal/59415163/MTO_Nuijten_replicability_robustness_and_reproducibility_Annual_Review_of_Psy_2022.pdf>
    * *A manifesto for reproducible science* <https://www.nature.com/articles/s41562-016-0021>
  * Regression Modeling:
    * *Introduction to Poisson Regression, Beyond Multiple Linear Regression* <https://bookdown.org/roback/bookdown-BeyondMLR/ch-poissonreg.html>
    * *Poisson Regression* <https://rpubs.com/franzbischoff/poisson_regression>
    * *Logistic Regression, Beyond Multiple Linear Regression* <https://bookdown.org/roback/bookdown-BeyondMLR/ch-logreg.html>
    
## Video Recording 

<iframe width="100%" height="500" src="https://www.youtube.com/embed/CUxrO5VVvgM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Resources
<a href="https://docs.google.com/document/d/1xKPn8J8dOTaVjbjobr5ZJSlG2kVrHy60xUK6op4eMpE/edit?usp=share_link"> link to daily google doc </a>
<br>
<a href="https://drive.google.com/drive/folders/1UdR07C-MJct5XH6u0EVcI_NEhZabGF4m?usp=share_link"> link to PDF slides</a>


### Lecture 1: Reproducibility and Robustness
<iframe src="https://id529.github.io/lectures/day5/lecture1-reproducibility-and-robustness/reproducibility.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures/day5/lecture1-reproducibility-and-robustness/reproducibility.html" >link to view slides fullscreen</a>
<br>
<a href="https://drive.google.com/file/d/1x5qKKmHCIaHb2KJvkvioVHSUBUkdrGEy/view?usp=share_link" > link to slide PDFs </a>
<br>

### Lecture 2: Regression (part 2!)

<a href = "https://drive.google.com/file/d/1F00Sko2LFk3kuPQ3SE2yG9Kmg1Lv0lVC/view?usp=share_link" > link to slide PDFs</a> 
<br>
<a href="https://github.com/jarvischen01/id529-regression-models" >link to repository</a></iframe>
<br> 


### Lecture 3: Data linkage methods

<iframe src="https://id529.github.io/lectures/day5/lecture3-data-linkage-methods/data-linkage-methods.html" width="100%" height="500px"></iframe> 
<a href="https://id529.github.io/lectures/day5/lecture3-data-linkage-methods/data-linkage-methods.html" >link to view slides fullscreen</iframe>
<br> 
<a href = "https://drive.google.com/file/d/1zRK9SjnezNTPJY_32THw8idemghkTuDQ/view?usp=share_link" > link to slide PDFs </a> 
<br> 
<a href="https://github.com/ID529/lectures/blob/main/day5/lecture3-data-linkage-methods/nhanes-activity.R" >link to follow along code</a>
<br> 