---
title: "Day 6 — Tuesday, January 17th, 2022"
sidebar:
  style: "floating"
  search: true
  contents: auto
---

## Tuesday January 17th

  * 1:30-1:50 Activity: Discussion of Onikye et al reproduction article
  * 1:50-2:10 Lecture: Introduction to R Packages 
  * 2:10-2:30 Demonstration of how to create R packages that standardize data loading and cleaning processes
  * 2:30-3:00 Lecture: How to use R Markdown to produce reproducible reports including tables, visualizations, and inline-quantitative statements.
  * 3:00-3:10 Break
  * 3:10-3:30 Activity: Experiment with different R Markdown features
  * 3:30-3:50 Lecture: Advice for Debugging
  * 3:50-4:10 Activity: Debugging
  * 4:10-4:30 Activity: Getting Help Online
  * 4:30-4:45 Demonstration of how to do the homework
  * 4:45-5:30 Time to do the homework, work on the final project together, peruse recommended materials
  
### Homework 5: 

  * Use R Markdown to document some exploratory data analyses

### Recommended Materials: 

  * R Packages: 
    * Read Karl Broman's [*Why write an R package?*](https://kbroman.org/pkg_primer/pages/why.html)
    * Familiarize yourself with what's in the R Packages book: <https://r-pkgs.org/>
    — having a rough familiarity with the different parts will be helpful. Our
    suggestion here is to try and approach this more in terms of "what are the
    ingredients in a good R Package?" rather than trying to learn how to craft all
    of those ingredients from the ground up immediately.
  * R Markdown: 
    * Check out the Get Started for R Markdown, especially the ~1 minute video intro on the 
    first page: <https://rmarkdown.rstudio.com/lesson-1.html>
    * [*How R Helps Airbnb Make the Most of Its Data*](https://peerj.com/preprints/3182.pdf)
    * If you find yourself loving R Markdown, you may find the [*R Markdown Cookbook*](https://bookdown.org/yihui/rmarkdown-cookbook/)
    useful, but it is incredibly comprehensive and we'd suggest it's better to reference 
    as you need it than to try to read it cover-to-cover.
    
## Video Recording
<iframe width="100%" height="500" src="https://www.youtube.com/embed/OKx2f8qrXmI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Resources
<a href="https://docs.google.com/document/d/1J2N0UoZrYPOy5UwSLNZ5bLibdefPgw9NqhnBor8tk7g/edit?usp=share_link"> link to daily google doc </a>
<br>
<a href="https://drive.google.com/drive/folders/186K4cgmkrUNuOfN3di3dbABwRNCi1UZL?usp=sharing"> link to PDF slides</a>


### Lecture 1: Packages
<iframe src="https://id529.github.io/lectures/day6/lecture1-packages/packages.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures/day6/lecture1-packages/packages.html" >link to view slides fullscreen</a>
<br>
<a href="https://drive.google.com/file/d/1P7qmW4QSDXZ8LJxZOgpldJHs4MRTiCzC/view?usp=share_link" > link to slide PDFs </a>
<br>

### Lecture 2: RMarkdown

<iframe src="https://id529.github.io/lectures/day6/lecture2-rmarkdown/intro-to-rmarkdown.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures/day6/lecture2-rmarkdown/intro-to-rmarkdown.html" >link to view slides fullscreen</a>
<br>
<a href="https://drive.google.com/file/d/1nOq-y1We0bKaFvFiLCgE_N4AjR2vyk7u/view?usp=share_link" > link to slide PDFs </a>
<br>

### Lecture 3: Debugging
<iframe src="https://id529.github.io/lectures/day6/lecture3-debugging/debugging.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures/day6/lecture3-debugging/debugging.html" >link to view slides fullscreen</a>
<br>

<a href="https://drive.google.com/file/d/1xsTx775VVd3HsfiZo08IT9nyIkPRjOol/view?usp=share_link"> link to slide PDFs </a>
<br>

<a href="https://gist.github.com/ctesta01/9d5fff579af66aa044c8789e7adffb6a"> link to live coding example reproducing a map of literacy rates in India from Wikipedia </a>
<br>