---
title: "Day 7 — Wednesday, January 18th, 2022"
sidebar:
  style: "floating"
  search: true
  contents: auto
---

## Wednesday January 18th

  * 1:30-2:00 Lecture: A Data Analysis from Start to Finish 
  * 2:00-2:30 Lecture: Longitudinal Data Analysis
  * 2:30-3:00 Lecture: Best practices for reporting on missing data
  * 3:00-3:30 Lecture: Intro to accessible exploratory data analysis methods: Correlation, principal components analysis, variable importance
  * 3:30-3:40 Break
  * 3:40-4:00 Discussion: What are the ethical principles involved in data analysis? What are the risks involved?
  * 4:00-4:30 Lecture: Clean Code and Considerate Coding
  * 4:30-5:30 Free time to work together on the final project, chat with classmates, peruse recommended materials

### Homework: 

  * Peer Review Homework 5

### Recommended Materials: 

  * Harms and Ethics in Data Science and Machine Learning: 
    * The *Data Science Ethics* chapter from the *Modern Data Science with R* book: <https://mdsr-book.github.io/mdsr2e/ch-ethics.html>

    
## Video Recording
<iframe width="100%" height="500" src="https://www.youtube.com/embed/64LwElkfOuU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Resources

<a href="https://docs.google.com/document/d/1o8D9B5oy0xmaiFj6EM9oy75ijuN5LZHQQDVI_AxRtxo/edit?usp=sharing_eil_se_dm&ts=63c83998"> link to daily google doc </a>
<br>
<a href="https://drive.google.com/drive/folders/1hrSSk28uLum6r6LsXOhSB7z0TEUQrypR?usp=share_link"> link to PDF slides</a>

## Lecture 2: Exploratory data analysis -- Longitudinal data analysis
<a href="https://github.com/ID529/lectures/blob/69d500e7d0ecc02e0b5a1bbceb17c11fd3fa19db/day7/lecture2-longitudinal-data-analysis/longitudinal_eda.R"> link to longitudinal_eda.R script <a>
<br>
<a href="https://github.com/ID529/lectures/blob/69d500e7d0ecc02e0b5a1bbceb17c11fd3fa19db/day7/lecture2-longitudinal-data-analysis/make_simulated_data.R"> link to make_simulated_data.R script </a>

## Lecture 3: Missing data
<iframe src="https://id529.github.io/lectures/day7/lecture2-missing-data/missing-data.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures/day7/lecture2-missing-data/missing-data.html" >link to view slides fullscreen</a>
<br>
<a href="https://drive.google.com/file/d/1hXNs3z-491eOBDo3H5pvogbax1O8oM1R/view?usp=share_link" > link to slide PDFs </a>
<br>
<a href = "https://github.com/ID529/lectures/blob/69d500e7d0ecc02e0b5a1bbceb17c11fd3fa19db/day7/lecture2-missing-data/missing-demo.R" > link to missing-demo.R script </a>

## Lecture 4: Accessible exploratory data analysis

<a href= "https://github.com/ID529/lectures/blob/69d500e7d0ecc02e0b5a1bbceb17c11fd3fa19db/day7/lecture3-accessible-eda/eda.R"> link to eda.R script </a>

## Lecture 5: Clean code and considerate coding 
<iframe src="https://id529.github.io/lectures/day7/lecture4-clean-code-and-considerate-coding/clean_code.html" width="100%" height="500px"></iframe>