---
title: "Day 8 — Thursday, January 19th, 2022"
sidebar:
  style: "floating"
  search: true
  contents: auto
---

## Thursday January 19th

  * 1:30-2:00 Lecture/Demo: Principles for Data Analysis from Start to Finish
  * 2:00-2:30 Lecture: Functional Programming
  * 2:30-3:00 Discussion + Demo: When does it make sense to use functional programming?
  * 3:00-3:10 Break
  * 3:10-3:40 Lecture: [Students' Choice]
  * 3:40-4:10 Lecture: How to Keep Growing as a Programmer (and stay up to date)
  * 4:10-4:20 Details about turning in your final presentations
  * 4:20-5:30 Positive affirmations, free time to work together on final projects
  
### Homework: 

  * Work with classmates to finalize presentations and turn them in

### Recommended materials: 

  * Hadley Wickham on Many Models: <https://youtu.be/cU0-NrUxRw4>
  
## Video Recording 

<iframe width="100%" height="500" src="https://www.youtube.com/embed/ztKPu52UQfU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

Apologies the lecture recording didn't capture 
the first lecture of the day. 

## Resources

<br>
<a href="https://drive.google.com/drive/folders/1nagsDlsJAMYJJbqgolw9jxzgifME_7we?usp=share_link"> link to PDF slides</a>
<br>
<a href="https://docs.google.com/document/d/1Jlyhf-iJVroIPl-YcwGDDjkbHMmiJNLmxo1w_kb8LhE/edit#"> link to daily google doc </a>
<br>

### Lecture 1: Principles for data analysis
<iframe src="https://id529.github.io/lectures/day8/lecture1-principles-for-data-analysis/principles.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures/day8/lecture1-principles-for-data-analysis/principles.html"> link to view slides fullscreen </a>
<br>
<a href="https://drive.google.com/file/d/1UTPf78R_x2yoLq5NvDHPSEGIOn9MDf7P/view?usp=share_link"> link to PDF slides </a> 

### Lecture 2: Functional Programming

<a href="https://github.com/ID529/lectures/blob/abffdc14d085305f1710f73741a0d0f58c926f51/day8/lecture2-functional-programming/functional_programming.R"> link to functional_programming.R script </a>

### Lecture 3: dplyr (student choice)

<a href="https://github.com/ID529/lectures/blob/abffdc14d085305f1710f73741a0d0f58c926f51/day8/lecture3-students-choice/dplyr_demo.R"> dplyr_demo.R script </a>

### Lecture 4: Growing as a programmer
<iframe src="https://id529.github.io/lectures/day8/lecture4-growing-as-a-programmer/growing.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures/day8/lecture4-growing-as-a-programmer/growing.html"> link to view slides fullscreen </a>
<br> 
<a href="https://drive.google.com/file/d/17k1mQ-iY_CUsBMknJzxs7j38ycacmowS/view?usp=share_link">link to PDF slides</a>

