---
title: "Day 9 — Friday, January 19th, 2023"
format: html
---

## Friday January 20th

  * 1:30-4:30 Final Presentations:
    * Students will be divided into 10 groups with 10-12 minutes presentation time
    and 3-5 minutes for feedback from the instructional team and Q&A from the
    audience.
    * 15 minutes × 10 groups = ~2.5 hours
    * we'll make sure to take some breaks between every few groups
  * 4:30-5:00 Lecture: Recap of Key Takeaways 
  * 5:00-5:30: 
    * Make sure you've uploaded your presentation! 
    * Feedback and Course Evaluations

Enjoy being done with the class and go on to do great things with your newly
learned R skills!

## Video Recording 

<iframe width="100%" height="500" src="https://www.youtube.com/embed/mCBH1BuGe1I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

## Student Presentations 

### Clean Code and Code Hygeine

<object data="/assets/january2023_presentations/Clean Code and Code Hygiene.pdf" width='100%' height='500'></object>

### Code Commenting and Documentation

<object data="/assets/january2023_presentations/Code Commenting and Documentation.pdf" width='100%' height='500'></object>

### Data Dictionaries 

<object data="/assets/january2023_presentations/Data Dictionaries.pdf" width='100%' height='500'></object>

### Data Visualization (Group 1)

<object data="/assets/january2023_presentations/Data Visualization Group 1.pdf" width='100%' height='500'></object>

### Data Visualization (Group 2)

<object data="/assets/january2023_presentations/Data Visualization Group 2.pdf" width='100%' height='500'></object>

### Presenting Model Results

<object data="/assets/january2023_presentations/Presenting Model Results.pdf" width='100%' height='500'></object>

### Geographic Maps

<object data="/assets/january2023_presentations/Best Practices for Mapping.pdf" width='100%' height='500'></object>

## Final lecture: Recap

<iframe src="https://id529.github.io/lectures/day9/lecture1-course-recap/course-recap.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures/day9/lecture1-course-recap/course-recap.html"> link to view slides fullscreen </a>
<br>
<a href="https://drive.google.com/file/d/1Urr-93VPnBVYTnDG9Qr8evLNQwgcTPVS/view?usp=share_link"> link to PDF slides </a> 
