project:
  type: website
  output-dir: docs

website:
  title: "ID529: Data Management and Analytic Workflows in R"
  favicon: "/assets/logo.svg"
  navbar:
    left:
      - text: Home 
        href: index.qmd
        icon: house
      - href: about.qmd
        icon: file-richtext
      - text: Curriculum
        icon: mortarboard
        menu:
        - text: Day 1 — Monday January 9, 2022
          href: day1.qmd
        - text: Day 2 — Tuesday January 10, 2022
          href: day2.qmd
        - text: Day 3 — Wednesday January 11, 2022
          href: day3.qmd
        - text: Day 4 — Thursday January 12, 2022
          href: day4.qmd
        - text: Day 5 — Friday January 13, 2022
          href: day5.qmd
        - text: Day 6 — Tuesday January 17, 2022
          href: day6.qmd
        - text: Day 7 — Wednesday January 18, 2022
          href: day7.qmd
        - text: Day 8 — Thursday January 19, 2022
          href: day8.qmd
        - text: Day 9 — Friday January 20, 2022
          href: day9.qmd

format:
  html:
    theme: [lumen, styles.scss]
    toc: true
