---
title: "Day 4"
sidebar:
  style: "floating"
  search: true
  contents: auto
---

Outline of topics: 

  - Lecture: Diverse Data Sources (APIs [tidycensus, WHO, World Bank, qualtRics], scraping web data, datapasta)
  - Discussion: What kind of sources are students interested in using in their research or future work?
  - Lecture: How to handle factors and date-times
  - Lecture: Working with Regression Model Objects: constructing and analyzing them
  - Activity: Working with Regression Models
  - Lecture: Creating Maps in R 
  - Lecture: Reproducible Examples for Getting Help

::: {.callout-tip collapse='true'}
### Lecture 1: Diverse Data Sources
<iframe src="https://id529.github.io/lectures/day4/lecture1-diverse-data-sources/diverse_data_sources.html" width="100%" height="500px"></iframe>
:::

<a href="https://id529.github.io/lectures/day4/lecture1-diverse-data-sources/diverse_data_sources.html" >link to view slides fullscreen</a>
<br>
<a href="https://drive.google.com/file/d/16cV6LHFiNDLvVBHuECTCZszICyZBvcT3/view?usp=drive_link" > link to slide PDFs </a>

::: {.callout-tip collapse='true'}
### Lecture 2: Factors and Date-times
<iframe src="https://id529.github.io/lectures2024/day4/lecture2-factors-and-datetimes/fct_datetime.html" width="100%" height="500px"></iframe>
<a href="https://id529.github.io/lectures2024/day4/lecture2-factors-and-datetimes/fct_datetime.html" >link to view slides fullscreen</iframe>
<br>
<br> 
:::

<a href="https://id529.github.io/lectures/day4/factor_datetime_code/fct_datetime.R" >link to follow along code</a>
<br> 
<a href = "https://drive.google.com/file/d/1AW94hM70Rfk1e9XAGu3Nb0KiVjCH0dL_/view?usp=drive_link" > link to slide PDFs </a> 

### Lecture 3: Regression

<a href = "https://id529.github.io/lectures/day4/lecture3-regression/id529_modelingWorkflows.pdf" > link to slide PDFs</a> 
<br>
<a href="https://github.com/jarvischen01/id529-regression-models" >link to repository</a></iframe>

::: {.callout-tip collapse='true'}
### Lecture 4: Creating maps in R 
<iframe src="https://id529.github.io/lectures/day4/lecture4-mapping/making-maps-in-R.html" width="100%" height="500px"></iframe>
:::

<a href="https://id529.github.io/lectures/day4/lecture4-mapping/making-maps-in-R.html" >link to view slides fullscreen</a>
<br> 
<a href = "https://drive.google.com/file/d/1Gadu3hkoLJtTJhUxSrt_OpYXXEf9KBDo/view?usp=drive_link"> link to slide PDFs </a> 


::: {.callout-tip collapse='true'}
### Lecture 5: Reproducible examples for getting help in R
<br>
<iframe src="https://id529.github.io/lectures2024/day4/lecture5-reprex/reprex.html" width="100%" height="500px"></iframe>
:::
<a href="https://id529.github.io/lectures2024/day4/lecture5-reprex/reprex.html" >link to view slides fullscreen </a>
<br> 
<a href = "https://drive.google.com/file/d/1Zvo13PAlxBjTyCBPaXwstE5E1ufjRlL4/view?usp=drive_link" > link to slide PDFs </a> 

::: {.callout-tip collapse='true'}
## Last Year's Video Recording

<iframe width="100%" height="500" src="https://www.youtube.com/embed/Fuk6k8W2Mho" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
:::